---
title: "Diabetes Logistic Regression Model"
output: html_notebook
---

```{r}
# front-matter
rm(list = ls()) #clear the workspace

library(tidymodels)  # for the tune package, along with the rest of tidymodels

# Helper packages
library(rpart.plot)  # for visualizing a decision tree
library(vip)         # for variable importance plots
```

```{r}
data(PimaIndiansDiabetes2, package = "mlbench")

diabetes <- na.omit(PimaIndiansDiabetes2)

diabetes <- as_tibble(diabetes)
class(diabetes)

diabetes
```

```{r}
set.seed(123)
diabetes_split <- initial_split(diabetes, strata = diabetes)
diabetes_train <- training(diabetes_split)
diabetes_test <- testing(diabetes_split)
```

```{r}
# training set proportions by children
diabetes_train %>% 
  count(diabetes) %>% 
  mutate(prop = n/sum(n))

# test set proportions by children
diabetes_test  %>% 
  count(diabetes) %>% 
  mutate(prop = n/sum(n))
```

```{r}
lr_mod <-
  logistic_reg(penalty = tune(), mixture = tune()) %>%
  set_engine("glmnet")

lr_mod
```

```{r}
lr_grid <- grid_regular(penalty(),
                        mixture(),
                        levels = 10)

lr_grid
```

```{r}
lr_grid %>%
  count(penalty)
```

```{r}
set.seed(234)
diabetes_folds <- vfold_cv(diabetes_train)
diabetes_folds
```

```{r}
lr_workflow <-
  workflow() %>%
  add_model(lr_mod) %>%
  add_formula(diabetes ~ .)

lr_res <-
  lr_workflow %>%
  tune_grid(
    resamples = diabetes_folds,
    grid = lr_grid,
    control = control_grid(save_pred = TRUE),
    metrics = metric_set(roc_auc)
    )

lr_res
```

```{r}
lr_res %>%
  collect_metrics
```

```{r}
lr_res %>%
  show_best("roc_auc")
```


```{r}
best_lr <- lr_res %>%
  select_best("roc_auc")

best_lr
```
```{r}
lr_auc <-
  lr_res %>%
  collect_predictions(parameters = best_lr) %>%
  roc_curve(diabetes, .pred_neg) %>%
  mutate(model = "Logistic Regression")

autoplot(lr_auc)

library(data.table)
fwrite(lr_auc,'/Users/malcolmzerbe/practice_r/diabetes/project/volume/data/processed/lr_auc.csv')
```

```{r}
lr_final_wf <-
  lr_workflow %>%
  finalize_workflow(best_lr)

lr_final_wf
```

```{r}
lr_final_fit <-
  lr_final_wf %>%
  last_fit(diabetes_split)

lr_final_fit %>%
  collect_metrics

lr_final_fit %>% collect_predictions()
```

```{r}
lr_final_fit %>%
  collect_predictions() %>%
  roc_curve(diabetes, .pred_neg) %>%
  autoplot()
```

```{r}
final_lr <- extract_workflow(lr_final_fit)
final_lr
```

```{r}
#final_boost %>%
  #extract_fit_engine() %>%
  #rpart.plot(roundint = FALSE)
```

```{r}
final_lr %>%
  extract_fit_parsnip() %>%
  vip()
```

```{r}
args(logistic_reg)
```

