---
title: "Customer Churn Gradient Boosted Trees Model"
output: html_notebook
---

```{r, include = F, echo = F, warning = F}
# clear environment
rm(list = ls())

# load packages
library(tidyverse)
library(tidymodels)
library(xgboost)
library(vip)
library(doParallel)
```

```{r}
# load in train and test
churn_train_path <- './project/volume/data/interim/churn_train.csv'
churn_test_path <- './project/volume/data/interim/churn_test.csv'
  
churn_train <- read.csv(churn_train_path, stringsAsFactors = TRUE)
churn_test <- read.csv(churn_test_path, stringsAsFactors = TRUE)
```

```{r}
# create model specification
churn_gbt_spec <- boost_tree(mtry = tune(),
                            trees = tune(),
                            min_n = tune(),
                            tree_depth = tune()) %>%
                            #learn_rate = tune(),
                            #loss_reduction = tune(),
                            #sample_size = tune()) %>%
                 set_mode("classification") %>%
                 set_engine("xgboost")
churn_gbt_spec

#args(boost_tree)
```

```{r}
# create model recipe to preprocess data
churn_gbt_rec <- recipe(Churn ~ ., data = churn_train) %>%
                 update_role(customerID, new_role = "ID") %>%
                 step_dummy(all_nominal_predictors()) %>%
                 step_zv(all_predictors()) %>%
                 step_normalize(all_predictors())
churn_gbt_rec
```

```{r}
# create regular grid of values for tuning
churn_gbt_grid <- grid_regular(mtry(range = c(1, 30)),
                              trees(),
                              min_n(),
                              tree_depth(),
                              #learn_rate(),
                              #loss_reduction(),
                              #sample_size(range = c(527, 2636)),
                              levels = 10)
churn_gbt_grid
dim(churn_gbt_grid)
```

```{r}
churn_gbt_dummies <- churn_gbt_rec %>% prep() %>% juice()
finalize(mtry(), x = churn_gbt_dummies[, -1])
finalize(sample_size(), x = churn_gbt_dummies[, -1])
```


```{r}
# view values in grid
churn_gbt_grid %>% count(trees)
```

```{r}
set.seed(40)

# create cross-validation folds
churn_folds <- vfold_cv(churn_train, v = 5, strata = Churn)
glimpse(churn_folds)

# create validation set
churn_val <- validation_split(churn_train, strata = Churn, prop = 0.80)
glimpse(churn_val)
```

```{r}
# create workflow and tune along grid
all_cores <- parallel::detectCores(logical = FALSE)
cl <- makePSOCKcluster(all_cores)
registerDoParallel(cl)

set.seed(40)

churn_gbt_wf <- workflow() %>%
               add_recipe(churn_gbt_rec) %>%
               add_model(churn_gbt_spec)

churn_gbt_res <- churn_gbt_wf %>%
                tune_grid(resamples = churn_val,
                          grid = churn_gbt_grid,
                          control = control_grid(save_pred = TRUE,
                                                 save_workflow = TRUE),
                          metrics = metric_set(roc_auc))
```

```{r}
# collect cv results
churn_gbt_res %>% collect_predictions()
saveRDS(churn_gbt_res, './project/volume/data/processed/churn_gbt_res.rds')

churn_gbt_res %>% collect_metrics()
churn_gbt_res %>% show_best("roc_auc")

# select best hyperparameters
churn_best_gbt <- churn_gbt_res %>%
                 select_best("roc_auc")
churn_best_gbt
```

```{r}
# visualize model cv performance
churn_gbt_auc <- churn_gbt_res %>%
                collect_predictions(parameters = churn_best_gbt) %>%
                roc_curve(Churn, .pred_No) %>%
                mutate(model = "Gradient Boosted Trees")
autoplot(churn_gbt_auc)

write_csv(churn_gbt_auc, './project/volume/data/processed/churn_gbt_auc.csv')
```

```{r}
# finalize workflow
churn_gbt_final_wf <- churn_gbt_wf %>%
                      finalize_workflow(churn_best_gbt)
churn_gbt_final_wf
```

```{r}
# fit model on full training set and evaluate test performance
churn_split <- readRDS('./project/volume/data/interim/churn_split.rds')

set.seed(40)
churn_gbt_final_fit <- churn_gbt_final_wf %>%
                       last_fit(churn_split)

churn_gbt_final_fit %>% collect_metrics()
churn_gbt_final_fit %>% collect_predictions()
```

```{r}
# visualize model test performance
churn_gbt_final_fit %>% collect_predictions() %>% roc_curve(Churn, .pred_No) %>% autoplot()
```

```{r}
# extract final fitted workflow (recipe + model) for future use
churn_final_gbt_wf <- extract_workflow(churn_gbt_final_fit)
churn_final_gbt_wf
saveRDS(churn_final_gbt_wf, './project/volume/models/churn_final_gbt_wf.wf')
```

```{r}
# inspect variable importance
churn_final_gbt_wf %>% extract_fit_parsnip() %>% vip(num_features = 20)
```

