---
title: "NBA Random Forest Model"
output: html_notebook
---

```{r}
# front-matter
rm(list = ls()) #clear the workspace

library(tidymodels)  # for the tune package, along with the rest of tidymodels

# Helper packages
library(rpart.plot)  # for visualizing a decision tree
library(vip)         # for variable importance plots
library(ranger)
```

```{r}
nba <- fread('/Users/malcolmzerbe/practice_r/nba/project/volume/data/interim/nba.csv')

nba <- as_tibble(nba)
class(nba)

nba <- nba %>%
  mutate(TARGET_5Yrs = as.factor(TARGET_5Yrs))

# Make Valid Column Names 
colnames(nba) <- make.names(colnames(nba))

nba
```

```{r}
set.seed(123)
nba_split <- initial_split(nba, strata = TARGET_5Yrs)
nba_train <- training(nba_split)
nba_test <- testing(nba_split)
```

```{r}
# training set proportions by response
nba_train %>% 
  count(TARGET_5Yrs) %>% 
  mutate(prop = n/sum(n))

# test set proportions by response
nba_test  %>% 
  count(TARGET_5Yrs) %>% 
  mutate(prop = n/sum(n))
```

```{r}
tune_spec <- rand_forest(
                mtry = tune(),
                trees = tune(),
                min_n = tune()
              ) %>%
             set_engine("ranger", importance = "impurity") %>%
             set_mode("classification")

tune_spec
```

```{r}
forest_grid <- grid_regular(mtry(range = c(1, 10)),
                          trees(range = c(500, 1500)),
                          min_n(range = c(60, 120)),
                          levels = 5)

forest_grid
```

```{r}
forest_grid %>%
  count(mtry)

forest_grid %>%
  count(trees)

forest_grid %>%
  count(min_n)
```

```{r}
set.seed(234)
nba_folds <- vfold_cv(nba_train)
nba_folds
```

```{r}
set.seed(345)

forest_wf <- workflow() %>%
  add_model(tune_spec) %>%
  add_formula(TARGET_5Yrs ~ .)

forest_res <-
  forest_wf %>%
  tune_grid(
      resamples = nba_folds,
      grid = forest_grid,
      control = control_grid(save_pred = TRUE),
      metrics = metric_set(roc_auc)
      )

forest_res
```

```{r}
forest_res %>%
  collect_metrics
```

```{r}
#tree_res %>%
  #collect_metrics() %>%
  #mutate(tree_depth = factor(tree_depth)) %>%
  #ggplot(aes(cost_complexity, mean, color = tree_depth)) +
  #geom_line(size = 1.5, alpha = 0.6) +
  #geom_point(size = 2) +
  #facet_wrap(~ .metric, scales = "free", nrow = 2) +
  #scale_x_log10(labels = scales::label_number()) +
  #scale_color_viridis_d(option = "plasma", begin = .9, end = 0)
```

```{r}
forest_res %>%
  show_best("roc_auc")
```

```{r}
best_forest <- forest_res %>%
  select_best("roc_auc")

best_forest
```

```{r}
rf_auc <-
  forest_res %>%
  collect_predictions(parameters = best_forest) %>%
  roc_curve(TARGET_5Yrs, .pred_0) %>%
  mutate(model = "Random Forest")

autoplot(rf_auc)

library(data.table)
fwrite(rf_auc,'/Users/malcolmzerbe/practice_r/nba/project/volume/data/processed/rf_auc.csv')
```

```{r}
rf_final_wf <-
  forest_wf %>%
  finalize_workflow(best_forest)

rf_final_wf
```

```{r}
rf_final_fit <-
  rf_final_wf %>%
  last_fit(diabetes_split)

rf_final_fit %>%
  collect_metrics

rf_final_fit %>% collect_predictions()
```

```{r}
rf_final_fit %>%
  collect_predictions() %>%
  roc_curve(diabetes, .pred_neg) %>%
  autoplot()
```

```{r}
final_forest <- extract_workflow(rf_final_fit)
final_forest
```

```{r}
#final_forest %>%
  #extract_fit_engine() %>%
  #rpart.plot(roundint = FALSE)
```

```{r}
final_forest %>%
  extract_fit_parsnip() %>%
  vip()
```

```{r}
args(rand_forest)
```

